nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.5.1.cjs
npmAuthToken: $NPM_AUTH_TOKEN
npmRegistryServer: $NPM_REGISTRY_SERVER

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://mskelton.dev/yarn-outdated/v3'
